### PR TITLE
GH #73 Update LinkedIn Share URL

### LINKED ISSUE #73: Update LinkedIn Share button URL
## Bug Report
- LInkedIn has updated their sharing URL, the present one is no longer working.

## ScreenShots
image

### PR DESCRIPTION
**Pull request by NikhilJoshua**
Updated the share URL of LinkedIn Button.
Closes #73 

## Update
- As per LinkedIn Docs the old URLs also work but will forward to new URL

cc: @chandrapatel

### CODE REVIEW

**Comment by abhi3315** [comment]
@NikhilJoshua This PR seems to be working fine and I was also able to share the post on LinkedIn.

Why is it in the draft?

**Comment by NikhilJoshua** [comment]
@abhi3315 I was testing with old URLs as well, wasn't sure if the update to new URLs was needed. So I made it a draft.
And the PR also has the twitter UI related changes which shouldn't be there. 
You can
[] Remove the twitter related changes or rebase without conflicts (as you merged the another branch).
[] Check with old/new URLs see which one's appropriate
Push any new changes to this branch.

**Comment by abhi3315** [comment]
> Check with old/new URLs see which one's appropriate

As per this [thread](https://stackoverflow.com/questions/33426752/linkedin-share-post-url#:~:text=Take%20the%20URL%20you%20are,og%3A%20tags%20to%20oEmbed%20data.), the URL that you have changed is the latest. It is good to have the latest URL.

> Remove the twitter related changes or rebase without conflicts (as you merged the another branch).

Done,

@pooja-muchandikar I have tested the Plugin seems to be fine. Please test it by yourself whenever you got time. I have updated the plugin https://pooja-rtmedia.rt.gw/

**Comment by pooja-muchandikar** [comment]
@abhi3315 
Please let us know the branch in which you have made changes and do not update on any dev site.

**Comment by abhi3315** [comment]
Okay @pooja-muchandikar 

`fix/linkedin-sharelink-update` This is the branch to test.

**Comment by ank1traj** [comment]
Hi @abhi3315,

This issue has been fixed. 

Cc: @NikhilJoshua @pooja-muchandikar

**Comment by pooja-muchandikar** [comment]
@abhi3315 
Some CI checks are not passed can you please check on those?

**Comment by abhi3315** [comment]
> @abhi3315 Some CI checks are not passed can you please check on those?

@pooja-muchandikar I have run the phpcs inspection locally but there are no issues.

image

In [inspection details](https://github.com/rtCamp/rtsocial/runs/5370392170?check_suite_focus=true) there are no specific information of inspection failing.

@chandrapatel Can you help me out to understand what's wrong with the inspection?

**Comment by chandrapatel** [comment]
@abhi3315 Ask Sys team to investigate that issue.

**Comment by abhi3315** [comment]
@pooja-muchandikar CI checks are passed!

**Review by mangesh — APPROVED** [review]

**Pull request merged**
